version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3-node
        environment:
          RAILS_ENV: test
          POSTGRES_DB_DATABASE: circle_test
          POSTGRES_DB_USERNAME: ubuntu
          POSTGRES_DB_PASSWORD: ""

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          name: Installing postgres dependencies
          command: sudo apt install -y postgresql-client || true
      - run:
          name: Installing ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - run:
          name: Database Setup
          command: bundle exec rake -f spec/dummy db:create db:migrate --trace
      - run:
          name: Run appraisal tests
          command: bundle exec appraisal install && bundle exec appraisal rspec
      - run:
          name: Run standard tests
          command: cd spec/dummy && bundle exec rspec
